### ISSUE TITLE
org-sticky-header-mode has a bug for hydra package

### ISSUE THREAD

**Issue by c02y** [alphapapa/org-sticky-header#13]
Check https://github.com/abo-abo/hydra/issues/331 for details.

**Comment by alphapapa** [comment]
I have no idea how this package could possibly cause that issue.  I use both packages and have no problems.  I suspect it's not actually caused by this package.

To confirm this, please do this:

1.  Run `emacs -q`.
2.  Manually load `org-sticky-header` and activate the mode.
3.  Manually define one of the problematic hydras.
4.  Activate the hydra.

If you can confirm that it's actually a bug in this package, I'll reopen this issue.
