### ISSUE TITLE
README.org should explain how to customize the display of the sticky header line

### ISSUE THREAD

**Issue by jrmiller82** [alphapapa/org-sticky-header#23]
Thanks!

**Comment by alphapapa** [comment]
I don't understand what you mean.

**Comment by tjtrabue** [comment]
I believe that @jrmiller82 means he would appreciate some guidance on customizing the variables for the sticky header line, such as `org-sticky-header-full-path` and `org-sticky-header-heading-star`. If he indeed feels this way then I agree: a brief summary of the customizable variables found in this package would make a great addition to the README. I had to discover these variables and their options by running the command `customize-group` for the `org-sticky-header` group, which is easy for a seasoned Emacs user to do, but may not be terribly intuitive for beginners.

Thank you so much for this amazing package, by the way! It's delightful.

**Comment by alphapapa** [comment]
@tjtrabue Thanks for the kind words.  I'm glad it's useful to you.

Regarding documentation: Emacs is "the self-documenting editor."  Customization groups are the standard way to present options to the user for both third-party packages and ones built-in to Emacs.  Once a user knows of them, customization of anything is only a few keystrokes away, with a full explanation of what each option does.  

The readmes for my packages aren't intended as a beginner's guide to Emacs.  There are already numerous such resources on the Internet and within Emacs itself.

And I don't generally document individual customization options in them, because that would be redundant, extra work, and I'd have to remember to keep the readme updated with them every time I add one.  However, I do mention new options in the changelog, so that existing users know there's something new to customize.

**Comment by tjtrabue** [comment]
@alphapapa I understand. Thank you for the prompt response.
